<a href="https://colab.research.google.com/github/waghvaishnav/Deep-Learning-PlayGround-Hub/blob/main/Gradient_Descent_PyTorch_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
from google.colab import files
files.upload()

Saving bonus_dataset.csv to bonus_dataset (1).csv


{'bonus_dataset (1).csv': b'employee_id,performance,years_of_experience,projects_completed,bonus\r\nEMP_001,7,2,4,124\r\nEMP_002,4,1,4,82\r\nEMP_003,8,7,10,178\r\nEMP_004,5,7,8,138\r\nEMP_005,7,8,9,170\r\nEMP_006,10,5,8,186\r\nEMP_007,3,3,5,84\r\nEMP_008,7,8,9,170\r\nEMP_009,8,6,9,170\r\nEMP_010,5,3,6,110\r\nEMP_011,4,1,4,82\r\nEMP_012,8,3,5,144\r\nEMP_013,8,5,8,162\r\nEMP_014,3,3,6,86\r\nEMP_015,6,1,4,106\r\nEMP_016,5,5,8,126\r\nEMP_017,2,10,11,126\r\nEMP_018,8,7,8,174\r\nEMP_019,6,7,10,154\r\nEMP_020,2,9,11,120\r\nEMP_021,5,10,11,162\r\nEMP_022,1,10,13,118\r\nEMP_023,10,3,4,166\r\nEMP_024,6,7,8,150\r\nEMP_025,9,1,3,140\r\nEMP_026,1,4,7,70\r\nEMP_027,10,4,7,178\r\nEMP_028,3,5,7,100\r\nEMP_029,7,7,9,164\r\nEMP_030,4,7,10,130\r\nEMP_031,9,4,7,166\r\nEMP_032,3,7,9,116\r\nEMP_033,5,3,4,106\r\nEMP_034,3,6,7,106\r\nEMP_035,7,2,4,124\r\nEMP_036,5,10,11,162\r\nEMP_037,9,9,11,204\r\nEMP_038,7,5,6,146\r\nEMP_039,2,6,7,94\r\nEMP_040,4,4,7,106\r\nEMP_041,9,10,13,214\r\nEMP_042,2,7,8,102\r\nEMP_04

In [33]:
import pandas as pd
import torch

data = pd.read_csv("bonus_dataset.csv")

df = pd.DataFrame(data)

In [34]:
df.head(5)

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    2                   4    124
1     EMP_002            4                    1                   4     82
2     EMP_003            8                    7                  10    178
3     EMP_004            5                    7                   8    138
4     EMP_005            7                    8                   9    170

In [45]:
# the neural network takes an array of number

performance = torch.tensor(df['performance'].values,dtype=torch.float32)
year_of_experience = torch.tensor(df['years_of_experience'].values,dtype=torch.float32)
project_completed = torch.tensor(df['projects_completed'].values,dtype=torch.float32)
bonus = torch.tensor(df['bonus'].values,dtype=torch.float32)

In [46]:
# initializes the weights randomly
w1 = torch.rand(1,requires_grad=True)
w2 = torch.rand(1,requires_grad=True)
w3 = torch.rand(1,requires_grad=True)

# calculate the bias
bias = torch.rand(1,requires_grad=True)

w1,w2,w3,bias

(tensor([0.6342], requires_grad=True),
 tensor([0.8106], requires_grad=True),
 tensor([0.5975], requires_grad=True),
 tensor([0.8117], requires_grad=True))

In [58]:
# set the epochs

epochs = 1000

# set the learning rate

learning_rate = 0.001

for epoch in range(epochs):
  # make prediction
  predicted_bonus = (w1*performance + w2*year_of_experience + w3*project_completed + bias)

  # calculating loss (mean squared error)
  loss = ((bonus - predicted_bonus)**2).mean()

  # apply the backpropagation
  loss.backward()

  with torch.no_grad():
    w1 -= learning_rate * w1.grad
    w2 -= learning_rate * w2.grad
    w3 -= learning_rate * w3.grad
    bias -= learning_rate * bias.grad

  w1.grad.zero_()          # here we zeros to gradients due to accumulation and adds the new grad into them.
  w2.grad.zero_()
  w3.grad.zero_()
  bias.grad.zero_()

  if epoch % 100 == 0:
    print(f"epoch {epoch} , loss {loss.item():0.2f} ")


# for the better result we can adjust the epochs and learning rate.

epoch 0 , loss 0.01 
epoch 100 , loss 0.01 
epoch 200 , loss 0.01 
epoch 300 , loss 0.01 
epoch 400 , loss 0.01 
epoch 500 , loss 0.01 
epoch 600 , loss 0.01 
epoch 700 , loss 0.01 
epoch 800 , loss 0.01 
epoch 900 , loss 0.01 


In [59]:
w1.item(),w2.item(),w3.item(),bias.item()

(12.019063949584961, 5.934625625610352, 2.0872113704681396, 19.574132919311523)

In [62]:
predicted_bonus[0]

tensor(123.9257, grad_fn=<SelectBackward0>)

In [66]:
df.head(1)

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    2                   4    124

In [70]:
new_prediction = 7 * w1.item() + w2.item()* 2 + w3.item() * 4 + bias
new_prediction

tensor([123.9257], grad_fn=<AddBackward0>)